name: flutter_test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout
      - uses: subosito/flutter-action@v2 # https://github.com/marketplace/actions/flutter-action
        with:
          flutter-version: '3.10.1'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test